### ISSUE TITLE
Error: Unexpected authenticator counter: 0 (should be > 0)

### ISSUE THREAD

**Issue by jmatsushita** [passwordless-id/webauthn#27]
When using the [playground](https://webauthn.passwordless.id/demos/playground.html) both in Chrome on Desktop and Mobile (iOS):
 - I can `Register Device` succesfully with the default settings
 - When I press `Login` the client side details are filled up
 - But a toaster shows up with this error `Error: Unexpected authenticator counter: 0 (should be > 0)`  and the second server side area shows:
```
Resulting into:
...
```

**Comment by dagnelies** [comment]
*According to the WebAuthn specification*, this counter should increase each time authentication is triggered with the key... In theory. In practice, Windows and Android do respect that, but Apple sets it to zero... And I don't actually know if they increase it at all since I don't have such a device to test. 

I recommend to use `counter:-1` to verify the first attestation instead of 0. And I would be curious if they properly increase this counter afterwards.

**Comment by dagnelies** [comment]
I will also edit the playground accordingly soon
