### ISSUE TITLE
TypeError: Illegal invocation when registering with enpass

### ISSUE THREAD

**Issue by BennyThink** [passwordless-id/webauthn#73]
# Environment
* Enpass Password Manager: 6.9.3
* Google Chrome: Version 127.0.6533.100 (Official Build) (arm64)
* OS: macOS 14.5 (23F79)

Using the simple demo to register https://webauthn.passwordless.id/demos/basic

or bellow code hosted on a server
```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
  <script type="module">
    import { client } from "https://cdn.jsdelivr.net/npm/@passwordless-id/webauthn@2.0.4/dist/browser/webauthn.min.js";

    async function registerUser() {
      await client.register({
        challenge: 'ZHNhamhoYWRzamhkc2E=',
        user: 'John Doe'
      });
    }

    // Expose the function to the global scope
    window.registerUser = registerUser;

  </script>
</head>
<body>
<button onclick="registerUser()">register</button>
</body>
</html>
```

# result
<img width="1545" alt="iShot_2024-08-10_16 45 04" src="https://github.com/user-attachments/assets/7acdc94b-604f-4abb-8dc7-2d2f64e5ea7b">

```typescript
    const publicKey = response.getPublicKey(); //<------cause illegal invocation error
    if (!publicKey)
        throw "Non-compliant browser or authenticator!"

```

Not sure if this is an enpass issue or webauthn issue, other type of authenticator, i.e. iCloud, yubikey, bitwarden works.

# might be related
* https://github.com/aws-samples/amazon-cognito-passwordless-auth/issues/94
* https://1password.community/discussion/142554/passkey-implementation-issue-illegal-invocation

**Comment by dagnelies** [comment]
Hi @BennyThink . Indeed the problem lies with enpass (and a few other password managers).

Basically, citing the [specs](https://www.w3.org/TR/webauthn-3/#sctn-public-key-easy):

> User agents MUST be able to return a non-null value for [getPublicKey()](https://www.w3.org/TR/webauthn-3/#dom-authenticatorattestationresponse-getpublickey) when the [credential public key](https://www.w3.org/TR/webauthn-3/#credential-public-key) has a [COSEAlgorithmIdentifier](https://www.w3.org/TR/webauthn-3/#typedefdef-cosealgorithmidentifier) value of:

- -7 (ES256), where [kty](https://tools.ietf.org/html/rfc9052#name-cose-key-common-parameters) is 2 (with uncompressed points) and [crv](https://tools.ietf.org/html/rfc9053#name-double-coordinate-curves) is 1 (P-256).
- -257 (RS256).
- -8 (EdDSA), where [crv](https://tools.ietf.org/html/rfc9053#name-double-coordinate-curves) is 6 (Ed25519).
